config_version: 2
name: "c4aa86c4fe66"
mode: "single"

dataplaneapi:
  host: "127.0.0.1"
  port: 5555

  user:
  - name: haproxy
    insecure: true
    password: adminpwd

  transaction:
    transaction_dir: "/tmp/haproxy"

  advertised: {}


haproxy:
  config_file: "/bitnami/haproxy/conf/haproxy.cfg"
  haproxy_bin: "/opt/bitnami/haproxy/sbin/haproxy"

  reload:
    reload_delay: 5
    reload_cmd : "kill -s HUP 1"
    restart_cmd: "service haproxy restart"
    reload_strategy: custom
