services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ..:/workspaces:cached
      - nats-auth:/etc/nats-auth
  haproxy:
    build:
      context: .
      dockerfile: Dockerfile.haproxy
    network_mode: service:dev
  nats-auth:
    image: natsio/nats-box:0.13.8
    command:
      - /tmp/configure-nats
    volumes:
      - nats-auth:/etc/nats-auth
      - ./setup-scripts:/tmp
  nats-server:
    image: nats:alpine
    command:
      - -c
      - /etc/nats/resolver.conf
      - -D
    depends_on:
      - nats-auth
    network_mode: service:dev
    volumes:
      - nats-auth:/etc/nats

volumes:
  nats-auth:
