services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    network_mode: service:haproxy
    volumes:
      - ..:/loadbalancer-manager-haproxy:cached
  haproxy:
    build:
      context: .
      dockerfile: Dockerfile.haproxy
    ports:
      - "5555:5555"
